### ISSUE TITLE
Ignore `url` and `@import`

### ISSUE THREAD

**Issue by arb** [webpack/css-loader#102]
Provide a mechanism to ignore `url` and `@import`.

From GItter
> arb  can i use the CSS loader and make it ignore any @import or url()?
> sokra 12:59
> nope... but feel free to send a PR: css-loader?-url&-import

**Comment by RinatMullayanov** [comment]
+1 useful options

**Comment by Phoenixmatrix** [comment]
A note of interest is that the older versions (eg: 0.14.5) DID have that feature: `css?url=false`

**Comment by download13** [comment]
I could use this feature as well.

**Comment by djyde** [comment]
+1.

For example:

```css
@font-face {
  font-family: 'WhiteAdobeAndroid';
  src: url('file:///android_asset/fonts/AGaramondPro-Regular.otf') format('truetype'); 
}
```

I use a file url `file:///android_asset`, which only exists in Android platform. But css-loader would require `./file:///android_asset` folder. I have no idea how to bundle it only a normal text instead of `require`.
