### ISSUE TITLE
Properties lost with UglifyJsPlugin after upgrading to 0.15.5

### ISSUE THREAD

**Issue by gpbl** [webpack/css-loader#114]
I upgraded from 0.14.5 to 0.15.5 and I've found some parts of my styles not working correctly. Trying to isolate the problem, I've seen for example that this source:

``` css

.Swipe {
  position: relative;
  user-select: none;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}

.Swipe-container {
  overflow: hidden;
  visibility: hidden;
  position: relative;
}

.Swipe-wrapper {
  overflow: hidden;
  position: relative;
}

.Swipe-child {
  float: left;
  width: 100%;
  position: relative;
}
```

...after being auto-prefixed, get minified as 

``` css

.Swipe {
    position: relative;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%
}

.Swipe-container {
    visibility: hidden
}

.Swipe-container,.Swipe-wrapper {
    overflow: hidden;
    position: relative
}

.Swipe-child {
    float: left;
    width: 100%
}
/*# sourceMappingURL=main-131e2e34531d647cdb93.css.map*/
```

(the minified version has been re-indented with chrome dev tools)

Note how the `.Swipe-child` selector has lost its `position: relative`. The property stays if I remove `.Swipe-container,.Swipe-wrapper` block. 

Does anybody else have this kind of issues? Maybe it is related to #89 and #94.
