### ISSUE TITLE
importing local class name from another less/sass module with variable returns error

### ISSUE THREAD

**Issue by juhaelee** [webpack/css-loader#122]
I'm getting an error saying `Module not found: Error: Cannot resolve module` when I try and compose from a file that has a LESS/SASS variable.

For example, say I have a less file (A.less):
```less
@import "./styles/colors.less" // contains @black: #000000

.A {
   color: @black
}
```

and if I try and compose from a different less file (B.less):
```less
.B {
   composes: color from "./A.less"
}
```

I get the error. I believe it's because css-loader is trying to read the @import statement in A.less as a module?
