### ISSUE TITLE
Composing classes that have been @imported does not work

### ISSUE THREAD

**Issue by rtsao** [webpack/css-loader#125]
Suppose we have this:

`node_modules/my-module/foo.css`

``` css
@import "./bar.css";

.foo {
  color: red;
}
```

`node_modules/my-module/bar.css`

``` css
.bar {
  color: blue;
}
```

`main.css`

``` css
.main {
  composes: foo from "my-module/foo.css"; /* this works*/
  composes: bar from "my-module/foo.css"; /* undefined*/
}
```

`main.js`

``` javascript
var styles = require('./main.css');
// {main:  'foo__foo___2Eu5D undefined'}
```

**Comment by lucy-orbach** [comment]
Hi rtsao.
I just started using css modules but as I understood, you can't use @import (or @extend) from Sass (maybe because it interferes with the import from webpack -?). You have to relay on the way composes work. Instead of calling bar from foo.css, you can try:
` .main {
  composes: foo from "my-module/foo.css"; 
  composes: bar from "my-module/bar.css"; /* directly from bar.css*/
}`
Otherwise, you can create a new class bar in foo.css that composes from bar.css and then use it.

**Comment by geelen** [comment]
@rtsao I know this is an old issue, but I think it's to do with the fact that the `@import` is parsed first, loaded without `?modules` mode, which is then cached as a CSS file that exports nothing (i.e. `module.exports = {}`) so the composition statement doesn't find anything.

There is a solution, though — this should work:

```css
@import "./bar.css";

.main {
  composes: foo from "my-module/foo.css";
  composes: global(bar);
}
```

But, my guess is you probably want to drop the `@import` and just use `composes` the way @lucy-orbach suggested :ok_hand:
