### ISSUE TITLE
When using local scope, how can I apply multiple classNames conditionally?

### ISSUE THREAD

**Issue by brandondurham** [webpack/css-loader#128]
I have a `<Capsule />` component that requires _at least_ the `.base` class. There are two other classes that extend the  `.base` class:

``` css
.base {
    background-color: white;
    border-radius: 12px;
    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.07);
    box-sizing: border-box;
    color: rgb(114, 110, 101);
    font-size: 11px;
    margin-top: 24px;
    min-height: 54px;
    padding: 20px;
    position: relative;
}
.clickable {
    composes: base;
    cursor: pointer;
}
.withIcon {
    composes: base;
    padding-left: 62px;
}
```

Depending on where the `<Capsule />` is rendered, the `.clickable` and `.withIcon` classes aren't always needed. There are occasions when both  `.clickable` and `.withIcon` will be needed.

I know that I could create another class:

``` css
.clickableWithIcon {
    composes: clickable;
    composes: withIcon;
}
```

But that just seems silly to me. I can't account for every combination, and there will likely be more. What would be the recommended way of doing what [classNames](https://github.com/JedWatson/classnames) pulls off with global classes in React?
