### ISSUE TITLE
Using PostCSS and composing a class from a different file

### ISSUE THREAD

**Issue by ericmatthys** [webpack/css-loader#137]
I am using PostCSS with the simple vars plugin, as an example. I have the loaders set up like:
```
loader: 'style!css?modules!postcss'
```

```css
.link1 {
  composes: link2 from './Link2.css';
  color: $firstLinkColor;
}
```

```css
.link2 {
  color: $secondLinkColor;
}
```

In that example, `link2` won't be run through PostCSS so the variable won't be replaced, but the variable in `link1` will be replaced. If I remove the `composes`, both `link1` and `link2` are run through PostCSS and both variables are correctly replaced.
