### ISSUE TITLE
Importing Locals from other files

### ISSUE THREAD

**Issue by frank-weindel** [webpack/css-loader#152]
Hello. I've got components which I'm styling using css-loader locals. Some of these components are composed in a parent component. I want the parent component to be able to override some CSS within its children. Since all the classnames are using locals I can no longer just override the classname directly.

Example:

``` less
@import "../components/ChildComponent1/ChildComponent1.less";
@import "../components/ChildComponent2/ChildComponent2.less";


:local(.ParentComponent) {
  :local(.ChildComponent1-Class) {
    position: absolute;
    bottom: 22px;
    left: 20px;
  }

  :local(.ChildComponent1-AnotherClass) {
    position: absolute;
    bottom: 22px;
    left: 20px;
  }

  :local(.ChildComponent2-Class) {
    overflow: visible;
    position: relative;
    height: 330px;
  }
  :local(.ChildComponent2-AnotherClass) {
    position: absolute;
    top: 43px;
  }
}
```

Importing seems, at least intuitively, to be the way to go. The locals declared within each ChildComponent's less files would be available to the parent component's LESS file.

Is this supported in anyway? I looked at the 'composes' syntax. For one thing I couldn't get it to work. But at the same time it doesn't seem to do what I want anyway. It seems to just take style rules from another file and merge it together into a new local. Not actually exposing the real classnames used in the other
file.

**Comment by sokra** [comment]
The idea of local scope is to prevent you from doing this.

You shouldn't (and cannot) reference classes from other files in selectors.

**Comment by frank-weindel** [comment]
I disagree that the whole idea should be to prevent this. In general it should prevent CSS from various components from clashing, but I think you should still have the flexibility to override sub-component CSS if you need to, as long as you make it very explicit that is what you are aiming to do. I don't see why this couldn't be allowed in some way that would still respect the integrity of locals. Maybe by having some way to :export and :import CSS classes from other files?

**Comment by sokra** [comment]
>  I don't see why this couldn't be allowed in some way that would still respect the integrity of locals.

* All styles affecting the component are no longer in one file. Any CSS file could affect the component. I would want to avoid that.
* import/export is used in the wrong direction. Normally `export` affects the `import`. But in your example you are writting to a imported value. In JS this would be equal to: `require("module").value = 5;`. This is a bad pratice.
* Components are no longer standalone/reusable, but depend on the structure of other component. I would want to avoid that too.

---

If you still want to do it, you can try this:

``` css
:import("./parent.css") {
  parent-class: class;
}

.class {
  /* normal styles */
}

.parent-class > .class {
  /* styles when component is in parent */
}
```

This avoids at least the first two issues, but creates a dependency from the child component to the parent component, which makes the component less reuseable.

---

Solution:

* add a attribute to the child component, which affects the styling. Depending on whether the child component is used within the parent component, set or unset the attribute.

``` css
.class {
  /* normal styles */
}
.composed {
  /* style when component is composed */
  /* Choose an more appropriate name depending on use case */
}
```
