### ISSUE TITLE
URL handling in @keyframes blocks

### ISSUE THREAD

**Issue by madx** [webpack/css-loader#164]
When using the following CSS, I do have an error `Module not found: Error: Cannot resolve module` for the `url()` part in the `@keyframes` block:

``` css
.className {
  background-image: url("./image.png")
}

@keyframes anim {
  0% {
    background-image: url("./image.png")
  }
}
```

I added a simple test to `test/urlTest.js` to expose the behaviour:

``` js
test("keyframe background img", "@keyframes anim { background: green url('img.png') xyz }", [
  [1, "@keyframes anim { background: green url({./img.png}) xyz }", ""]
]);
```
