### ISSUE TITLE
Module not found: Error: Cannot resolve 'file' or 'directory' ./about:blank 

### ISSUE THREAD

**Issue by callmez** [webpack/css-loader#173]
``` css
*html{
    background-image:url(about:blank); 
    background-attachment:fixed;
}
```

is there any way to fix this problem?
