### ISSUE TITLE
Bug with loading images in css in devtools

### ISSUE THREAD

**Issue by LestaD** [webpack/css-loader#192]
I try:

``` css
# ./style.css
.searchBg {
  background-image: url(sprite/searchBg.jpg)
}
```

``` js
# ./component.js
import css from './style.css';

// begin component
  <div className={css.searchBg} />
// end component
```

What i see in chrome:
![image](https://cloud.githubusercontent.com/assets/5620073/11242182/32542fdc-8e11-11e5-8b93-3563b09b5abb.png)

But image not loading to background.
When i click on "Open Link in new tab", link opens as:

![image](https://cloud.githubusercontent.com/assets/5620073/11242207/58689ff0-8e11-11e5-9954-77ec78af2c74.png)
