### ISSUE TITLE
how can I just add suffix on the className, not a fully random string

### ISSUE THREAD

**Issue by huarse** [webpack/css-loader#238]
eg. 

```less
:local(.className) { background: red; }
:local .className { color: green; }
:local(.className .subClass) { color: green; }
:local .className .subClass :global(.global-class-name) { color: blue; }
```

I suggest the result should be like this: 

```css
.className_aKvs { background: red; }
.className_aKvs { color: green; }
.className_aKvs .subClass_MStbBE { color: green; }
.className_aKvs .subClass_MStbBE .global-class-name { color: blue; }
```
