### ISSUE TITLE
Problem compiling a spreadsheet

### ISSUE THREAD

**Issue by karlguillotte** [webpack/css-loader#249]
Just starting with css-modules. Trying to compile the file below. And I get the error below. Why am I getting that error? 

Thanks!

```
Error: composition is only allowed when selector is single :local class name not in ".primary", ".primary" is weird
```

```css
.common {
	font-family: Montserrat, Arial, sans-serif;
	font-size: 16px;
	font-weight: bold;
	text-transform: uppercase;
	color: white;
	padding: 20px 26px;
}

.primary {
	composes: common;
	background-color: blue;
}
```

**Comment by cehoffman** [comment]
@karlguillotte did you figure it out? Just starting with CSS modules myself and got the same problem. These feels just like the XKCD comic ![Wisdom of the Ancients](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

**Comment by karlguillotte** [comment]
@cehoffman  Ah ah! Like your picture. I should have posted the solution. Unfortunately, I do not remember the solution, but is an easy fix. Let's start with your CSS loader configuration. What is your configuration?

**Comment by cehoffman** [comment]
Thank @karlguillotte, use this loader configuration with webpack 2 beta and postcss is configured to use precss.

```javascript
    loaders: [{
      test: /\.css$/,
      loader: [
        'style',
        'css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]',
        'postcss',
      ],
    }],
```

**Comment by karlguillotte** [comment]
I have a similar configuration. 

Could you try adding a _s_ to _loader_?

https://webpack.github.io/docs/using-loaders.html#configuration

**Comment by samcorcos** [comment]
I ended up with the same problem, though I solved the error by changing the syntax to use [cssnext](http://cssnext.io/features/#custom-properties-set-apply).

```css
:root {
  --button {
    color: white;
    border-radius: 5px;
    border: 1px;
    padding: 0.8rem 2rem;
    cursor: pointer;
    font-size: 1em;
    align-self: center;
  }
}

.primary {
  @apply --button;
  background: rgb(239, 95, 78);
}
```

That said... my component still doesn't render with the proper styling. But it does render something!

My webpack config:

```js
  module: {
    loaders: [{
        test: /\.css$/,
        loader: ExtractTextPlugin.extract('style', 'css?modules&importLoaders=1&localIdentName=[local]_[hash:base64:5]!postcss')
      }]
  },
  postcss: function () {
    return [cssnext]
  },
```
