### ISSUE TITLE
Generated css file uses backslashes in url path on Windows

### ISSUE THREAD

**Issue by dfedynich** [webpack/css-loader#252]
I used the next loader in weback.config.js to manage css files

```javascript
{
    test: /\.css$/,
    loader: ExtractTextPlugin.extract("css")
}
```

There is the next line somewhere in the source code 

```javascript
require('jquery-ui/themes/base/jquery-ui.css')
```

jquery-ui.css file contains the next line:

```css
.class-name {
background-image: url(images/ui-bg_glass_75_e6e6e6_1x400.png)
}
```

After webpack generates css file for me when I run it on windows, this line will be converted to:

```css
.class-name: {
background-image: url(\jquery-ui\themes\base\images\ui-bg_glass_75_e6e6e6_1x400.png.png) 
}
```

These backslashes in the background url are interpreted as escape chars instead of slashes (\j \t etc.) and the path turns out like this 

```css
jquery-uithemesºseimagesui-bg_glass_75_e6e6e6_1x400.png.png
```
 CSS will accept both double backslashes (\\) or forward slashes as far as I know.
