### ISSUE TITLE
Does @value support a comma-separated list?

### ISSUE THREAD

**Issue by paulyoung** [webpack/css-loader#268]
For example:

_foo.css_
```css
@value font-family: "Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;
```

_bar.css_
```css
@value font-family from 'variables.css';

body {
  font-family: font-family;
}
```

_output.css_
```css
body {
  font-family: "Roboto";
}
```

***

I'm resorting to this in the meantime:

_foo.css_
```css
:export {
  font-family: "Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;
}
```

_bar.css_
```css
:import('variables.css') {
  font-family: font-family;
}
```

_output.css_
```css
body {
  font-family: "Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;
}
```

**Comment by paulyoung** [comment]
This also works:

_foo.css_

```css
:export {
  font-family: "Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;
}
```

_bar.css_

```css
@value font-family from 'variables.css';

body {
  font-family: font-family;
}
```

_output.css_

```css
body {
  font-family: "Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;
}
```
