### ISSUE TITLE
Can npm-managed packages use local root-relative urls?

### ISSUE THREAD

**Issue by mattfysh** [webpack/css-loader#31]
let's say I have ./node_modules/my-ui/src/style/main.css, and in this file I have
url("/images/my-image.png") as a reference to ./node_modules/my-ui/src/images/my-image.png

is there any way to allow each of the packages in node_modules use their own root-relative URL's?
when developing locally for my-ui, everything is fine since it defines ?root=src in its own webpack.config.js, but when my-ui is an npm dependency... how can it continue to use root-relative URL's in its CSS?

thanks!

**Comment by sokra** [comment]
You should better use relative urls like this: `url("../images/my-image.png")`.

But you can use different settings for different paths:

``` js
module.loaders: [
  {
    test: /\.css$/,
    include: /my-ui.src.style/,
    loader: "style!css?root=../"
  },
  {
    test: /\.css$/,
    exclude: /my-ui.src.style/,
    loader: "style!css"
  }
]
```

**Comment by mattfysh** [comment]
hmmm.. not sure why the consumer of a module should have to specify root=, especially when there are many consumers. you have to keep repeating this internal package knowledge across all consumers...

that's quite messy, especially when the internals of the package change and you need to go updating in 10/100+ places...

**Comment by sokra** [comment]
> You should better use relative urls like this: url("../images/my-image.png").

**Comment by jhnns** [comment]
With webpack and the [file-loader](https://github.com/webpack/file-loader) you usually don't need to use root-urls. Just use a relative url and webpack will translate it:

```css
.some-class {
   background: url(../images/my-image.png);
}
```

with [`output.publicPath`](http://webpack.github.io/docs/configuration.html#output-publicpath) being `"/assets/"` becomes

```css
.some-class {
   background: url(/assets/678g7sdg87sd76s8d7g6s.png);
}
```

**Comment by roman01la** [comment]
I have `bootstrap-styl` installed in `node_modules` dir with relative urls to Bootstrap fonts and `file-loader` for all the fonts. Styles loader is running like this: `style-loader!css-loader!stylus-loader`. The output of the `stylus-loader` is ok, but it seems `css-loader` cannot resolve font files:
```
ERROR in ./~/css-loader!./~/stylus-loader?paths=node_modules/!./styl/main.styl
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/glyphicons-halflings-regular.eot in /Users/roman01la/projects/test/styl
```

**Comment by jhnns** [comment]
Take a look at [this issue](https://github.com/jtangelder/sass-loader/issues/40) at the sass-loader. It's the exact same problem, maybe you'll find an answer there.

**Comment by roman01la** [comment]
@jhnns Thank you! Wondering is there a way to resolve relative path from webpack config or something?

**Comment by jhnns** [comment]
You probably can leverage css-loader's [root-relative urls](https://github.com/webpack/css-loader#root-relative-urls)?

**Comment by roman01la** [comment]
> If a root query parameter is set, however, it will be prepended to the url and then translated

Here's my loader `style-loader!css-loader?root=./styl/!stylus-loader?paths=node_modules/`, but it seems `./styl/` path is ignored, because `styl` is a random empty dir and build is still successful.

**Comment by jasonkuhrt** [comment]
There is something inaccurate or unclear. According to @sokra This should work:

```
@font-face {
  font-family: 'Futura Round';
  src: url('./fonts/FuturaRoundLight.woff') format('woff');
  font-weight: 100;
  font-style: normal;
}
```

But it fails with:

```
ERROR in ./~/css-loader!./~/cssnext-loader!./client/index.css
Module not found: Error: Cannot resolve 'file' or 'directory' ./fonts/FuturaRoundLight.woff in /Users/jasonkuhrt/projects/www-developers/client
 @ ./~/css-loader!./~/cssnext-loader!./client/index.css 2:9233-9273
```

forcing me to this incantation:
```
@font-face {
  font-family: 'Futura Round';
  src: url('~futura-round-family/fonts/FuturaRoundLight.woff') format('woff');
  font-weight: 100;
  font-style: normal;
}
```

**Comment by sokra** [comment]
Did you `@import` the `@font-face` file?

Could be this issue: https://github.com/webpack/css-loader/issues/34

**Comment by jasonkuhrt** [comment]
@sokra sorry I don't understand your question. It sounds like you are asking if I did this:

```css
@import './fonts/FuturaRoundLight.woff';
```

But that makes no sense.

Maybe helpful, here is my webpack config in the project that consumes the `futura-round-family` dependency:

```js
var join = require('path').join



module.exports = {
  name: 'browser',
  entry: {
    index: ['webpack/hot/dev-server', './client/index.js']
  },
  output: {
    path: join(__dirname, 'client/build'),
    filename: '[name].js'
  },
  module: {
    loaders: [
      { test: /\.js$/, loader: '6to5!uglify' },
      { test: /\.woff$/, loader: 'url' },
      { test: /\.css$/, loader: 'style!css!cssnext' },
      { test: /\.json$/, loader: 'json' },
      { test: /\.yaml$/, loader: 'json!yaml' }
    ]
  },
  devtool: 'sourcemap',
  console: true
}

```

**Comment by jhnns** [comment]
Are the less file and the `./fonts/FuturaRoundLight.woff` file in the same project?

**Comment by jasonkuhrt** [comment]
@jhnns It is a `css` file not `less`. The `futura-round-family` module lives here https://github.com/littlebitselectronics/futura-round-family but we had to make it private because of the font license (sigh...). In this module we have a `package.json` that looks like this:

```
{
  "name": "futura-round-family",
  "version": "1.0.0",
  "description": "The [Futura Round](http://www.youworkforthem.com/font/T4800/futura-round) type family.",
  "main": "index.css",
  "repository": {
    "type": "git",
    "url": "https://github.com/littlebitselectronics/futura-round-family.git"
  },
  "author": "Jason Kuhrt <jasonkuhrt@me.com> (http://jasonkuhrt.com/)",
  "bugs": {
    "url": "https://github.com/littlebitselectronics/futura-round-family/issues"
  },
  "homepage": "https://github.com/littlebitselectronics/futura-round-family"
}
```

More generally the project FS looks like:

![screen shot 2015-01-25 at 2 03 05 pm](https://cloud.githubusercontent.com/assets/284476/5892818/edae8108-a49a-11e4-9166-6e96d11fc91c.png)

Where `index.css` has this content:

```css
@font-face {
  font-family: 'Futura Round';
  src: url('~futura-round-family/fonts/FuturaRoundLight.woff') format('woff');
  font-weight: 100;
  font-style: normal;
}

@font-face {
  font-family: 'Futura Round';
  src: url('~futura-round-family/fonts/FuturaRoundBook.woff') format('svg');
  font-weight: 300;
  font-style: normal;
}

@font-face {
  font-family: 'Futura Round';
  src: url('~futura-round-family/fonts/FuturaRoundMedium.woff') format('woff');
  font-weight: 400;
  font-style: normal;
}

@font-face {
  font-family: 'Futura Round';
  src: url('~futura-round-family/fonts/FuturaRoundDemi.woff') format('woff');
  font-weight: 600;
  font-style: normal;
}

@font-face {
  font-family: 'Futura Round';
  src: url('~futura-round-family/fonts/FuturaRoundBold.woff') format('woff');
  font-weight: 700;
  font-style: normal;
}
```

Sorry if none of this is helping you understand my issue. I'll keep trying to explain/show.
