### ISSUE TITLE
Module build failed: SyntaxError: Unexpected token h

### ISSUE THREAD

**Issue by MoOx** [webpack/css-loader#33]
The following CSS ia breaking my build

```css
.class {
  filter: drop-shadow(0 1px 0 var(--vr-Color-white));
}
```
It's totally valid CSS. It seems related to the parser. Maybe you should consider using a better parser like postcss ?

**Comment by sokra** [comment]
Could you paste the complete error

**Comment by MoOx** [comment]
```
ERROR in ./~/css-loader!./~/cssnext-loader!./src/index.css
Module build failed: SyntaxError: Unexpected token h
    at Object.parse (native)
    at Object.parseString (/.../node_modules/css-loader/node_modules/loader-utils/index.js:152:14)
    at(/.../node_modules/css-loader/index.js:47:25
    at String.replace (native)
    at Object.module.exports (/.../node_modules/css-loader/index.js:45:12)
 @ ./src/index.css 4:14-293 12:19-298
```

**Comment by sokra** [comment]
Oh you are using the css-loader... So the real css code is different:

This:

``` css
:root {
  --vr-Color-white: white;
}

.class {
  filter: drop-shadow(0 1px 0 var(--vr-Color-white));
}
```

transpiles to this:

```
.class {
  filter: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg"><filter id="filter"><feGaussianBlur in="SourceAlpha" stdDeviation="0" /><feOffset dx="1" dy="2" result="offsetblur" /><feFlood flood-color="rgba(255,255,255,1)" /><feComposite in2="offsetblur" operator="in" /><feMerge><feMergeNode /><feMergeNode in="SourceGraphic" /></feMerge></filter></svg>#filter');
  -webkit-filter: drop-shadow(0 1px 0 white);
          filter: drop-shadow(0 1px 0 white);
}
```
