### ISSUE TITLE
Cannot do relative require() for resource via url()

### ISSUE THREAD

**Issue by MoOx** [webpack/css-loader#34]
I've a stylesheet that use a font but using relative url (relative to the css) doesn't work.

In `src/path/style.css` the following CSS doesn't work ("cannot found" error)

```css
@font-face {
  font-family: 'myFont;
  src: url("./myFont.otf");
}
```

I had to use

```css
@font-face {
  font-family: 'myFont;
  src: url("src/path/myFont.otf");
}
```

But it's not how require() should work right ?
