### ISSUE TITLE
Using the same class names with CSS Modules (Webpack 2)

### ISSUE THREAD

**Issue by azat-io** [webpack/css-loader#364]
Hi there!

I'm using:
- **webpack** v.2.1.0-beta.25
- **css-loader** v.0.25.0

Here is a part of my `webpack.babel.config.js`:

``` js
{
    test: /\.css$/,
    exclude: [
        '/node_modules/',
        '/public/',
    ],
    loaders: [
        'style-loader',
        'css-loader?modules&localIdentName=[local]--[hash:base64:5]' +
            '!postcss-loader',
     ],
}
```

In my project there is a folder `components`. I this folder there are a lot of React components.
#### Form

Here is a `components/Form/index.jsx`

``` js
import React, { Component } from 'react'
import styles from './index.css'

class Form extends Component {
    render () {
        return (
            <form>
                <h1 className={ styles.title }>
                    { 'Contact me' }
                </h1>
            </form>
        )
    }
}

export default Form
```

And `components/Form/index.css`:

``` css
.title {
    font-size: 1.35em;
    color: rgba(0, 0, 0, 0.85);
}
```
#### Content

`components/Content/index.jsx`

``` js
import React, { Component } from 'react'
import styles from './index.css'

class Content extends Component {
    render () {
        return (
            <div>
                <h1 className={ styles.title }>
                    { 'Content' }
                </h1>
            </div>
        )
    }
}

export default Content
```

`components/Content/index.css`

``` css
.title {
    flex: 1 1 100%;
    font-size: 1.35em;
    color: #fff;
    text-align: center;
}
```

After building app both `.title` selectors has the same hash. Looks pretty strange

What's wrong? :thinking:
