### ISSUE TITLE
Single or double quotes in comments causing failure in resolving url()

### ISSUE THREAD

**Issue by fenivana** [webpack/css-loader#62]
```css
/*
 * a ' above
 */

.bg {
  background-image: url(bg.jpg);
}

/*
 * a ' below
 */
```

bg.jpg won't get resolved. A slice of the output :
```js
exports.push([module.id, "/*\n * a ' above\n */\n\n.bg {\n  background-image: url(bg.jpg);\n}\n\n/*\n * a ' below\n */\n", ""]);
```

Both single and double quotes can cause this bug.
