### ISSUE TITLE
When extend child class, parent class is also extended

### ISSUE THREAD

**Issue by meoguru** [webpack/css-loader#63]
I have this piece of CSS:

```css
/* test.css */

.topbar {
  /* blah */
}

.topbar .search {
  extends: iconMagnifier from "../../styles/icons.scss";
}
```

After running through `css-loader` with:

```js
{
  test: /\.css$/,
  loaders: [
    'style',
    'css?module'
  ]
}
```

I got something like that with exported styles:

```js
import styles from "./test.css";
console.log(styles);
// => { topbar: "topbar--hhDqN iconMagnifier--28gN4", search: "search--1hPrb iconMagnifier--28gN4" }
```

`topbar` should not be extended like that, right? Styles should be `{ topbar: "topbar--hhDqN", search: "search--1hPrb iconMagnifier--28gN4" }`.

Though?
