### ISSUE TITLE
0.15 breaks escaped characters

### ISSUE THREAD

**Issue by mathieumg** [webpack/css-loader#79]
```css
.myclass:before {
  content: "\f0e3";
}
```

now compiles to

```css
.myclass:before {
  content: "f0e3";
}
```
