### ISSUE TITLE
Base64 SVG does not load in new version

### ISSUE THREAD

**Issue by mech** [webpack/css-loader#85]
Hi using version 0.14.5, my SVG style using base64 can be loaded:

```css
.svg-preview {
  background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbjXXX....');
}
```

However upgrading to version 0.15.1, the browser no longer able to load it :(

Any idea? Don't think is my SVG source file as it can be loaded previously.
